modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/AllyEffect/issues"
license="MIT"

[[mods]]
modId="allyeffect"
version="${file.jarVersion}"
displayName="Ally Effect"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ally-effect"
authors="Mrbysco, nekomaster1000"
description='''
Heal your friends at the cost of hunger by hugging them!
'''

[[dependencies.allyeffect]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="allyeffect.mixins.json"